import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by drizzle-kit from db/schema.ts -- edits here are overwritten on
    // the next `npm run db:generate`.
    "db/migrations/**",
  ]),
  {
    // `_name` is the established convention here for a binding that exists only to
    // be discarded, e.g. stripping `evidence_quote` off an extracted item with rest
    // destructuring in cron/extract.ts.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // `.cjs` files are CommonJS by definition -- `scripts/env.cjs` is preloaded with
    // `tsx --require`, which cannot take an ES module. Flagging `require()` there is
    // the rule misfiring on the one file format where it is the only option.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
]);

export default eslintConfig;
